
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy

  export const environment = {
    production: false,
    EXCHANGE_RATE_API_KEY: 'c5c6b17efbf52ed9c95d14d3'
  };
